<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="80564" started-at="2015-10-21T11:32:20Z" finished-at="2015-10-21T11:33:41Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="80564" started-at="2015-10-21T11:32:20Z" finished-at="2015-10-21T11:33:41Z">
      <class name="com.houzify.scripts.HZActionsTest">
        <test-method status="PASS" signature="setobjects()[pri:0, instance:com.houzify.scripts.HZActionsTest@2669b199]" name="setobjects" is-config="true" duration-ms="13" started-at="2015-10-21T17:02:20Z" finished-at="2015-10-21T17:02:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setobjects -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.houzify.scripts.HZActionsTest@2669b199]" name="setUp" is-config="true" duration-ms="38531" started-at="2015-10-21T17:02:20Z" finished-at="2015-10-21T17:02:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testSwipe()[pri:0, instance:com.houzify.scripts.HZActionsTest@2669b199]" name="testSwipe" duration-ms="40300" started-at="2015-10-21T17:02:59Z" finished-at="2015-10-21T17:03:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.houzify.scripts.HZActionsTest.testSwipe(HZActionsTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSwipe -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.houzify.scripts.HZActionsTest@2669b199]" name="tearDown" is-config="true" duration-ms="1698" started-at="2015-10-21T17:03:39Z" finished-at="2015-10-21T17:03:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.houzify.scripts.HZActionsTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
